server:
  port: 9050

spring:
  kafka:
    newTopic: new_topic22
    topics: messages4
    bootstrap-servers: localhost:9092
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.memorynotfound: DEBUG
